/**
 * Content layer — CMS agent implementation.
 *
 * All page content is loaded from static JSON files in /content/[locale]/.
 * Files are generated by scripts/transform-cms.py from Webflow CSV exports.
 *
 * File structure:
 *   /content/[locale]/[collection-type]/[slug].json
 *
 * Security: all content is loaded from the local filesystem at build time.
 * No user input reaches these paths; slugs are validated before use.
 */

import fs from "fs";
import path from "path";

// ---------------------------------------------------------------------------
// Core types (re-exported for consumers)
// ---------------------------------------------------------------------------

export type Locale = "en" | "de" | "fr" | "es";

export const SUPPORTED_LOCALES: Locale[] = ["en", "de", "fr", "es"];

export interface SeoMeta {
  title: string;
  description: string;
  canonical: string;
  ogImage?: string;
  noIndex?: boolean;
}

export interface HrefLangEntry {
  locale: Locale;
  href: string;
}

/** Common fields every page content object must include. */
export interface PageContentBase {
  slug: string;
  locale: Locale;
  seo: SeoMeta;
  hrefLangs: HrefLangEntry[];
  updatedAt?: string;
}

/** Generic section for page builder */
export interface ContentSection {
  /** Must match the Webflow section class name for traceability */
  sectionId: string;
  type: string;
  data: Record<string, unknown>;
}

export interface PageContent extends PageContentBase {
  sections: ContentSection[];
}

/** CMS collection item (typed fields from Webflow export) */
export interface CmsCollectionItem extends PageContentBase {
  collectionType: string;
  fields: Record<string, unknown>;
}

export interface Navigation {
  locale: Locale;
  mainLinks: NavLink[];
  ctaLabel: string;
  ctaHref: string;
  footerColumns: FooterColumn[];
  legalLinks: NavLink[];
  copyright: string;
}

export interface NavLink {
  label: string;
  href: string;
  hasDropdown?: boolean;
  children?: NavLink[];
}

export interface FooterColumn {
  heading: string;
  links: NavLink[];
}

// ---------------------------------------------------------------------------
// Path helpers
// ---------------------------------------------------------------------------

const CONTENT_ROOT = path.join(process.cwd(), "content");

/**
 * Validate a slug to prevent path traversal attacks.
 * Slugs must be URL-safe: lowercase alphanumeric, hyphens, underscores only.
 */
function assertSafeSlug(slug: string): void {
  if (!/^[a-z0-9_-]+$/.test(slug)) {
    throw new Error(
      `Invalid slug "${slug}" — only lowercase alphanumeric, hyphens and underscores allowed`
    );
  }
}

/**
 * Validate a locale is one of the supported values.
 */
function assertValidLocale(locale: string): asserts locale is Locale {
  if (!SUPPORTED_LOCALES.includes(locale as Locale)) {
    throw new Error(
      `Invalid locale "${locale}" — must be one of: ${SUPPORTED_LOCALES.join(", ")}`
    );
  }
}

/**
 * Validate a collection name to prevent path traversal.
 * Collections use kebab-case alphanumeric names.
 */
function assertSafeCollection(collection: string): void {
  if (!/^[a-z0-9-]+$/.test(collection)) {
    throw new Error(
      `Invalid collection name "${collection}" — only lowercase alphanumeric and hyphens allowed`
    );
  }
}

/**
 * Read and parse a JSON file. Returns null if the file does not exist.
 * Throws on malformed JSON or permission errors.
 */
function readJsonFile<T>(filePath: string): T | null {
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    // Security: parse with JSON.parse which does not execute code
    return JSON.parse(raw) as T;
  } catch (err: unknown) {
    if (
      err instanceof Error &&
      "code" in err &&
      (err as NodeJS.ErrnoException).code === "ENOENT"
    ) {
      return null;
    }
    throw new Error(
      `Failed to read content file "${filePath}": ${err instanceof Error ? err.message : String(err)}`
    );
  }
}

// ---------------------------------------------------------------------------
// Page content loader
// ---------------------------------------------------------------------------

/**
 * Load a single page's content by slug and locale.
 *
 * File location: /content/[locale]/pages/[slug].json
 * Returns null if the file does not exist (caller should return 404).
 */
export async function getPageContent(
  locale: Locale,
  slug: string
): Promise<PageContent | null> {
  assertValidLocale(locale);
  assertSafeSlug(slug);

  const filePath = path.join(CONTENT_ROOT, locale, "pages", `${slug}.json`);
  const data = readJsonFile<PageContent>(filePath);

  if (data === null) {
    return null;
  }

  // Runtime validation: ensure required fields are present
  if (!data.slug || !data.locale || !data.seo || !Array.isArray(data.sections)) {
    throw new Error(
      `Content file "${filePath}" is malformed — missing required fields (slug, locale, seo, sections)`
    );
  }

  return data;
}

// ---------------------------------------------------------------------------
// CMS collection item loader
// ---------------------------------------------------------------------------

/**
 * Load a CMS collection item by collection type, slug, and locale.
 *
 * File location: /content/[locale]/[collection]/[slug].json
 * Returns null if the file does not exist.
 */
export async function getCollectionItem(
  locale: Locale,
  collection: string,
  slug: string
): Promise<CmsCollectionItem | null> {
  assertValidLocale(locale);
  assertSafeCollection(collection);
  assertSafeSlug(slug);

  const filePath = path.join(CONTENT_ROOT, locale, collection, `${slug}.json`);
  const data = readJsonFile<CmsCollectionItem>(filePath);

  if (data === null) {
    return null;
  }

  // Runtime validation
  if (!data.slug || !data.locale || !data.collectionType) {
    throw new Error(
      `Collection item file "${filePath}" is malformed — missing required fields (slug, locale, collectionType)`
    );
  }

  return data;
}

// ---------------------------------------------------------------------------
// Slug listing (for generateStaticParams)
// ---------------------------------------------------------------------------

/**
 * List all slugs available for a collection in a given locale.
 *
 * Used by Next.js generateStaticParams to build all static routes.
 * Returns empty array if the directory does not exist.
 */
export async function listCollectionSlugs(
  locale: Locale,
  collection: string
): Promise<string[]> {
  assertValidLocale(locale);
  assertSafeCollection(collection);

  const dirPath = path.join(CONTENT_ROOT, locale, collection);

  if (!fs.existsSync(dirPath)) {
    return [];
  }

  const files = fs.readdirSync(dirPath);
  return files
    .filter((f) => f.endsWith(".json"))
    .map((f) => f.replace(/\.json$/, ""));
}

/**
 * List all page slugs for a given locale.
 *
 * File location: /content/[locale]/pages/
 */
export async function listPageSlugs(locale: Locale): Promise<string[]> {
  return listCollectionSlugs(locale, "pages");
}

// ---------------------------------------------------------------------------
// Navigation loader
// ---------------------------------------------------------------------------

/**
 * Load navigation data for the given locale.
 *
 * File location: /content/[locale]/navigation/main.json
 * Throws if navigation data is missing (nav is required for every page).
 */
export async function getNavigation(locale: Locale): Promise<Navigation> {
  assertValidLocale(locale);

  const filePath = path.join(CONTENT_ROOT, locale, "navigation", "main.json");
  const data = readJsonFile<Navigation>(filePath);

  if (data === null) {
    throw new Error(
      `Navigation content missing for locale "${locale}" — expected at ${filePath}. ` +
        `Run scripts/transform-cms.py to generate content files.`
    );
  }

  // Runtime validation
  if (!data.locale || !Array.isArray(data.mainLinks)) {
    throw new Error(
      `Navigation file "${filePath}" is malformed — missing required fields (locale, mainLinks)`
    );
  }

  return data;
}

// ---------------------------------------------------------------------------
// Bulk loader — all items in a collection
// ---------------------------------------------------------------------------

/**
 * Load all items in a collection for a given locale.
 *
 * Useful for listing pages (e.g. /integrations, /case-studies).
 * Returns an empty array if the collection directory does not exist.
 */
export async function getAllCollectionItems(
  locale: Locale,
  collection: string
): Promise<CmsCollectionItem[]> {
  const slugs = await listCollectionSlugs(locale, collection);
  const items = await Promise.all(
    slugs.map((slug) => getCollectionItem(locale, collection, slug))
  );
  // Filter out nulls (shouldn't happen, but defensive)
  return items.filter((item): item is CmsCollectionItem => item !== null);
}

// ---------------------------------------------------------------------------
// hrefLang helper
// ---------------------------------------------------------------------------

/**
 * Build hreflang entries for a given slug and collection.
 *
 * Use this when generating page metadata to produce alternate language links.
 * All 4 locales are included; if a locale file is missing, it is omitted.
 */
export async function buildHrefLangs(
  collection: string,
  slug: string,
  baseUrl: string = "https://www.synup.com"
): Promise<HrefLangEntry[]> {
  const entries: HrefLangEntry[] = [];

  for (const locale of SUPPORTED_LOCALES) {
    const filePath = path.join(
      CONTENT_ROOT,
      locale,
      collection,
      `${slug}.json`
    );
    if (fs.existsSync(filePath)) {
      const urlPath =
        locale === "en"
          ? `/${collection}/${slug}`
          : `/${locale}/${collection}/${slug}`;
      entries.push({ locale, href: `${baseUrl}${urlPath}` });
    }
  }

  return entries;
}
